apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: default
type: Opaque
data:
  username: aXNod2FyaWttdDc=
  password: Mkx2MnMzOHVrZWhQNkF6Zg==
  connection_string: bW9uZ29kYitzcnY6Ly9pc2h3YXJpa210NzoyTHYyczM4dWtlaFA2QXpmQHNpdDczNy52cXJpbWF4Lm1vbmdvZGIubmV0Lw==